package gbrain_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sirerun/serenity/internal/config"
	"github.com/sirerun/serenity/internal/domain"
	"github.com/sirerun/serenity/internal/import/gbrain"
	"github.com/sirerun/serenity/internal/store"
)

// Expectations are hand-written independently of Map, not generated by the
// implementation under test. The same test accepts a pinned external fixture.
func TestGBrainFieldRoundTrip(t *testing.T) {
	source := os.Getenv("SERENITY_GBRAIN_FIXTURE")
	if source == "" {
		source = fixture
	}
	root := brain(t)
	result, err := gbrain.Import(context.Background(), source, root, config.Default())
	if err != nil {
		t.Fatal(err)
	}
	if result.Audit.Rows != 8 || result.Audit.Fields != 74 || len(result.Audit.Unmapped) != 0 {
		t.Fatalf("field report: %+v", result.Audit)
	}
	type expectation struct {
		page, fence, row, object, predicate, from, to, visibility, state, successor, source, context, notability, who, weight string
		confidence                                                                                                            float64
	}
	rows := []expectation{
		{"people/ava.md", "facts", "1", "Use a hard cutover", "committed_to", "2026-01-01", "2026-02-01", "shared", "superseded", "facts#2", "meeting: one", "superseded by #2", "high", "", "", .9},
		{"people/ava.md", "facts", "2", "Prefer feature flags", "prefers", "2026-02-01", "", "private", "active", "", "email: two", "choice | rationale", "medium", "", "", .85},
		{"people/ava.md", "facts", "3", "Old contact detail", "relates_to", "2025-01-01", "2026-01-01", "private", "retracted", "", "imported notes", "forgotten: user request", "low", "", "", .7},
		{"people/ava.md", "facts", "4", "Presented the plan", "said", "2026-03-01", "2026-03-01", "shared", "active", "", "calendar", `C:\notes\ava`, "high", "", "", .8},
		{"people/ava.md", "facts", "5", "Tests prevent regressions", "relates_to", "", "", "private", "active", "", "conversation", "", "medium", "", "", .6},
		{"people/ava.md", "takes", "1", "Migration will finish", "said", "2026-02", "2026-04", "private", "active", "", "planning", "", "", "people/ava", "0.95", .9},
		{"people/ava.md", "takes", "2", "Obsolete prediction", "said", "2025-12", "", "private", "retracted", "", "historical", "", "", "brain", "0.20", .2},
		{"projects/beacon.md", "facts", "1", "Synthetic project", "relates_to", "2026-01", "", "shared", "active", "", "fixture", "", "low", "", "", .9},
	}
	claims := map[string]domain.Claim{}
	ids := map[string]bool{}
	fw := store.NewFenceWriter(root)
	for _, e := range []struct{ typ, slug string }{{"person", "ava"}, {"project", "beacon"}} {
		p, err := fw.ParseEntity(fw.PathFor(e.typ, e.slug))
		if err != nil {
			t.Fatal(err)
		}
		for _, c := range p.Claims {
			m := c.Provenance.Meta
			key := m["gbrain_page"] + "|" + m["gbrain_fence"] + "#" + m["#"]
			if _, ok := claims[key]; ok {
				t.Fatalf("duplicate row %s", key)
			}
			if ids[c.ID] {
				t.Fatalf("collapsed independent rows into %s", c.ID)
			}
			ids[c.ID] = true
			claims[key] = c
		}
	}
	if len(claims) != len(rows) {
		t.Fatalf("got %d claims for %d source rows", len(claims), len(rows))
	}
	for _, e := range rows {
		t.Run(e.page+"/"+e.fence+e.row, func(t *testing.T) {
			c, ok := claims[e.page+"|"+e.fence+"#"+e.row]
			if !ok {
				t.Fatal("source row missing")
			}
			checks := map[string][2]string{"object": {e.object, c.Object}, "predicate": {e.predicate, c.Predicate}, "valid_from": {e.from, c.ValidFrom}, "valid_to": {e.to, c.ValidTo}, "visibility": {e.visibility, string(c.Visibility)}, "state": {e.state, string(c.State)}, "source": {e.source, c.Provenance.Meta["source"]}, "context": {e.context, c.Provenance.Meta["context"]}, "notability": {e.notability, c.Provenance.Meta["notability"]}, "who": {e.who, c.Provenance.Meta["who"]}, "weight": {e.weight, c.Provenance.Meta["weight"]}, "source_ref": {"gbrain:" + strings.TrimSuffix(e.page, ".md") + "#" + e.row, c.SourceRef}}
			for field, pair := range checks {
				if pair[0] != pair[1] {
					t.Errorf("%s: expected %q, got %q", field, pair[0], pair[1])
				}
			}
			if c.Confidence != e.confidence || !c.Review {
				t.Errorf("confidence/review: %+v", c)
			}
			successor := ""
			if e.successor != "" {
				successor = claims[e.page+"|"+e.successor].ID
			}
			if c.SupersededBy != successor {
				t.Errorf("superseded pointer %q, expected %q", c.SupersededBy, successor)
			}
			if e.who != "" && c.Provenance.Actor != e.who {
				t.Errorf("actor %q, expected %q", c.Provenance.Actor, e.who)
			}
			if e.row == "3" && c.Provenance.Meta["forgotten_reason"] != "forgotten: user request" {
				t.Error("forgotten reason lost")
			}
		})
	}
}

func TestAuditNamesMissingAndChangedFields(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(fixture, "people/ava.md"))
	if err != nil {
		t.Fatal(err)
	}
	p, err := gbrain.Parse("people/ava.md", raw)
	if err != nil {
		t.Fatal(err)
	}
	mapped, err := gbrain.Map(p)
	if err != nil {
		t.Fatal(err)
	}
	delete(mapped.Claims[0].Provenance.Meta, "context")
	mapped.Claims[1].Visibility = domain.VisibilityShared
	report := gbrain.Audit(p, mapped.Claims)
	if len(report.Unmapped) != 2 {
		t.Fatalf("expected exactly two losses: %+v", report)
	}
	found := map[string]bool{}
	for _, loss := range report.Unmapped {
		found[fmt.Sprintf("%s#%d:%s", loss.Fence, loss.Row, loss.Field)] = true
	}
	if !found["facts#1:provenance.context"] || !found["facts#2:visibility"] {
		t.Fatalf("incorrect field diagnostics: %+v", report.Unmapped)
	}
}

func TestRoundTripRetainsExtensionColumns(t *testing.T) {
	source := t.TempDir()
	raw := `---
type: person
---
# Ada
<!--- gbrain:facts:begin -->
| # | claim | kind | confidence | visibility | notability | valid_from | valid_until | source | context | metric | value | unit | period | future_column |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | A typed claim | fact | 0.12345 | private | low | 2026-01 | | report | context | arr | 50000.00 | USD | annual | keep exactly |
<!--- gbrain:facts:end -->
<!--- gbrain:takes:begin -->
| # | claim | kind | who | weight | since | source | resolved | quality | evidence | value | unit | by |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | A resolved prediction | bet | people/ada | 0.75 | 2025-01 → 2026-01 | notes | 2026-01-02 | partial | observed result | 12.30 | units | ada |
<!--- gbrain:takes:end -->
`
	if err := os.WriteFile(filepath.Join(source, "ada.md"), []byte(raw), 0o600); err != nil {
		t.Fatal(err)
	}
	root := brain(t)
	result, err := gbrain.Import(context.Background(), source, root, config.Default())
	if err != nil {
		t.Fatal(err)
	}
	if result.Audit.Fields != 28 || len(result.Audit.Unmapped) != 0 {
		t.Fatalf("report: %+v", result.Audit)
	}
	fw := store.NewFenceWriter(root)
	p, err := fw.ParseEntity(fw.PathFor("person", "ada"))
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range p.Claims {
		m := c.Provenance.Meta
		if m["gbrain_fence"] == "facts" {
			if m["value"] != "50000.00" || m["future_column"] != "keep exactly" || c.Confidence != .12345 {
				t.Fatalf("typed fields lost: %+v", c)
			}
		} else if m["resolved"] != "2026-01-02" || m["quality"] != "partial" || m["value"] != "12.30" || m["by"] != "ada" {
			t.Fatalf("resolution fields lost: %+v", c)
		}
	}
}
