//go:build ignore

// Command gen_manifest re-pins testdata/conformance/memory_verbs/MANIFEST
// after a deliberate change to this directory's vendored gbrain fixtures,
// using internal/conformance's checksum tooling unmodified (T4.13, same
// pattern evals/corpora/direction/gen_manifest.go and
// evals/corpora/ava/gen_corpus.go already establish for their own
// checksum-pinned corpora via internal/eval). Run it from the repo root
// after adding, editing, or removing a file in this directory:
//
//	GOWORK=off go run testdata/conformance/memory_verbs/gen_manifest.go
//
// (GOWORK=off per docs/lore.md L-0001 -- unnecessary from an offloaded
// worktree, required from a plain sirerun/serenity checkout.)
//
// This directory's own files (cases.json, LICENSE) are not generated by
// this script -- they are vendored by hand from
// dndungu/gbrain@d35c9c9e441e (see README.md in this directory for the
// exact provenance and re-vendoring procedure). This script only re-pins
// the checksum manifest after such a hand vendoring step.
package main

import (
	"log"

	"github.com/sirerun/serenity/internal/conformance"
)

func main() {
	const dir = "testdata/conformance/memory_verbs"
	if err := conformance.WriteManifest(dir); err != nil {
		log.Fatalf("gen_manifest: %v", err)
	}
}
