// Package store implements the canonical brain-repo writers (RFC §7):
// gbrain-style fenced entity pages and append-only JSONL claim shards.
// Both writers are deterministic — parse → edit → render round-trips
// byte-identically — so git merges resolve deterministically and rebuilds
// are reproducible.
package store

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/sirerun/serenity/internal/domain"
)

// Fence markers. The summary fence is DERIVED (machine-regenerated); the
// claims fence is machine-written but human-repairable — for fence-tier
// families the file is truth (§7.2). Shard-tier head rows are derived and
// carry src "shard" (§7.2a).
const (
	beginSummary = "<!-- serenity:summary:begin (DERIVED — regenerated by consolidate; do not hand-edit) -->"
	endSummary   = "<!-- serenity:summary:end -->"
	beginClaims  = "<!-- serenity:claims:begin -->"
	endClaims    = "<!-- serenity:claims:end -->"
	beginDetail  = "<!-- serenity:claims-detail:begin -->"
	endDetail    = "<!-- serenity:claims-detail:end -->"
	beginTL      = "<!-- serenity:timeline:begin -->"
	endTL        = "<!-- serenity:timeline:end -->"

	claimsHeader    = "| id | predicate | object | conf | valid | src | state |"
	claimsSeparator = "|----|-----------|--------|------|-------|-----|-------|"

	// objectCellMax is the head-cell cap (§7.2): longer objects move to
	// the claims-detail block keyed by id; the cell holds the head.
	objectCellMax = 120
)

// TimelineEntry is one line of the timeline fence.
type TimelineEntry struct {
	Date string
	Text string
}

// EntityPage is the structured form of one entity markdown page.
type EntityPage struct {
	Entity   domain.Entity
	Title    string
	Summary  string
	Claims   []domain.Claim
	Timeline []TimelineEntry
}

// NewEntityPage builds an empty page with the title derived from the slug.
func NewEntityPage(e domain.Entity) *EntityPage {
	return &EntityPage{Entity: e, Title: titleFromSlug(e.Slug)}
}

// FenceWriter renders and parses entity pages under root/brain/entities.
type FenceWriter struct {
	Root string
}

func NewFenceWriter(root string) *FenceWriter { return &FenceWriter{Root: root} }

// PathFor returns the canonical page path: brain/entities/<type>/<slug>.md.
func (w *FenceWriter) PathFor(entityType, slug string) string {
	return filepath.Join(w.Root, "brain", "entities", entityType, slug+".md")
}

// RenderEntity emits the exact canonical byte form of a page. Claims and
// timeline entries are sorted so concurrent git merges are deterministic
// (§7.2: rows are append-mostly; the writer sorts and normalizes).
func (w *FenceWriter) RenderEntity(p *EntityPage) ([]byte, error) {
	for i := range p.Claims {
		if strings.ContainsRune(p.Claims[i].Object, '\n') {
			return nil, fmt.Errorf("claim %s: objects must be single-line (canonical form)", p.Claims[i].ID)
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "---\ntype: %s\nslug: %s\n", p.Entity.Type, p.Entity.Slug)
	if len(p.Entity.Aliases) > 0 {
		fmt.Fprintf(&b, "aliases: [%s]\n", strings.Join(p.Entity.Aliases, ", "))
	}
	b.WriteString("---\n")

	title := p.Title
	if title == "" {
		title = titleFromSlug(p.Entity.Slug)
	}
	fmt.Fprintf(&b, "# %s\n\n", title)

	b.WriteString(beginSummary + "\n" + p.Summary + "\n" + endSummary + "\n\n")

	// Canonical form: cell values carry no leading/trailing whitespace
	// (parse trims cell padding, so untrimmed values cannot round-trip).
	// Normalize before sorting so ordering is stable across round trips.
	claims := append([]domain.Claim(nil), p.Claims...)
	for i := range claims {
		claims[i].Predicate = strings.TrimSpace(claims[i].Predicate)
		claims[i].Object = strings.TrimSpace(claims[i].Object)
		claims[i].SourceRef = strings.TrimSpace(claims[i].SourceRef)
	}
	sort.Slice(claims, func(i, j int) bool {
		a, c := claims[i], claims[j]
		if a.Predicate != c.Predicate {
			return a.Predicate < c.Predicate
		}
		if a.Object != c.Object {
			return a.Object < c.Object
		}
		return a.ID < c.ID
	})

	details := map[string]string{}
	b.WriteString(beginClaims + "\n" + claimsHeader + "\n" + claimsSeparator + "\n")
	for _, c := range claims {
		obj := c.Object
		if r := []rune(obj); len(r) > objectCellMax {
			details[c.ID] = obj
			obj = string(r[:objectCellMax-3]) + "…"
		}
		idCell := c.ID
		if c.State == domain.StateSuperseded {
			idCell = "~~" + c.ID + "~~"
		}
		stateCell := string(c.State)
		if c.SupersededBy != "" {
			stateCell = "superseded→" + c.SupersededBy
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
			escapeCell(idCell), escapeCell(c.Predicate), escapeCell(obj),
			confCell(c.Confidence), windowCell(c.ValidFrom, c.ValidTo),
			escapeCell(c.SourceRef), escapeCell(stateCell))
	}
	b.WriteString(endClaims + "\n\n")

	if len(details) > 0 {
		ids := make([]string, 0, len(details))
		for id := range details {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		b.WriteString(beginDetail + "\n")
		for _, id := range ids {
			fmt.Fprintf(&b, "- %s: %s\n", id, details[id])
		}
		b.WriteString(endDetail + "\n\n")
	}

	tl := append([]TimelineEntry(nil), p.Timeline...)
	for i := range tl {
		tl[i].Date = strings.TrimSpace(tl[i].Date)
		tl[i].Text = strings.TrimSpace(tl[i].Text)
	}
	sort.Slice(tl, func(i, j int) bool {
		if tl[i].Date != tl[j].Date {
			return tl[i].Date < tl[j].Date
		}
		return tl[i].Text < tl[j].Text
	})
	b.WriteString(beginTL + "\n")
	for _, t := range tl {
		fmt.Fprintf(&b, "- %s: %s\n", t.Date, t.Text)
	}
	b.WriteString(endTL + "\n")
	return b.Bytes(), nil
}

// ParseEntity reads a page back into structured form, preserving human
// edits: for fence-tier families the file is truth (§7.2).
func (w *FenceWriter) ParseEntity(path string) (*EntityPage, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("parse entity: %w", err)
	}
	return ParseEntityBytes(raw)
}

// ParseEntityBytes parses page content (exported for tests and rebuild).
func ParseEntityBytes(raw []byte) (*EntityPage, error) {
	s := string(raw)
	p := &EntityPage{}

	fm, rest, err := splitFrontmatter(s)
	if err != nil {
		return nil, err
	}
	for _, ln := range strings.Split(fm, "\n") {
		key, val, ok := strings.Cut(ln, ": ")
		if !ok {
			continue
		}
		switch key {
		case "type":
			p.Entity.Type = val
		case "slug":
			p.Entity.Slug = val
		case "aliases":
			val = strings.TrimPrefix(strings.TrimSuffix(val, "]"), "[")
			if val != "" {
				p.Entity.Aliases = strings.Split(val, ", ")
			}
		}
	}

	for _, ln := range strings.Split(rest, "\n") {
		if after, ok := strings.CutPrefix(ln, "# "); ok {
			p.Title = after
			break
		}
	}

	if body, ok := section(s, beginSummary, endSummary); ok {
		p.Summary = strings.TrimSuffix(strings.TrimPrefix(body, "\n"), "\n")
	}

	details := map[string]string{}
	if body, ok := section(s, beginDetail, endDetail); ok {
		for _, ln := range strings.Split(body, "\n") {
			ln = strings.TrimSpace(ln)
			if entry, ok := strings.CutPrefix(ln, "- "); ok {
				if id, text, ok := strings.Cut(entry, ": "); ok {
					details[id] = text
				}
			}
		}
	}

	if body, ok := section(s, beginClaims, endClaims); ok {
		for _, ln := range strings.Split(body, "\n") {
			ln = strings.TrimSpace(ln)
			if !strings.HasPrefix(ln, "|") || ln == claimsHeader || strings.HasPrefix(ln, "|--") {
				continue
			}
			cells := splitRow(ln)
			if len(cells) != 7 {
				continue
			}
			c := domain.Claim{
				SubjectSlug: p.Entity.Slug,
				Predicate:   cells[1],
				Object:      cells[2],
				SourceRef:   cells[5],
			}
			c.ID = cells[0]
			if inner, ok := strings.CutPrefix(c.ID, "~~"); ok {
				c.ID = strings.TrimSuffix(inner, "~~")
			}
			if conf, err := strconv.ParseFloat(cells[3], 64); err == nil {
				c.Confidence = conf
			}
			if from, to, ok := strings.Cut(cells[4], ".."); ok {
				c.ValidFrom, c.ValidTo = from, to
			} else {
				c.ValidFrom = cells[4]
			}
			switch {
			case strings.HasPrefix(cells[6], "superseded→"):
				c.State = domain.StateSuperseded
				c.SupersededBy = strings.TrimPrefix(cells[6], "superseded→")
			default:
				c.State = domain.State(cells[6])
			}
			if full, ok := details[c.ID]; ok && strings.HasSuffix(c.Object, "…") {
				c.Object = full
			}
			c.Family = c.Predicate // families are 1:1 with predicates in the seed vocabulary
			p.Claims = append(p.Claims, c)
		}
	}

	if body, ok := section(s, beginTL, endTL); ok {
		for _, ln := range strings.Split(body, "\n") {
			ln = strings.TrimSpace(ln)
			if entry, ok := strings.CutPrefix(ln, "- "); ok {
				if date, text, ok := strings.Cut(entry, ": "); ok {
					p.Timeline = append(p.Timeline, TimelineEntry{Date: date, Text: text})
				}
			}
		}
	}
	return p, nil
}

// WriteEntity renders and writes the page, skipping the write when bytes
// are unchanged so no-op cycles never dirty the working tree.
func (w *FenceWriter) WriteEntity(p *EntityPage) (string, error) {
	path := w.PathFor(p.Entity.Type, p.Entity.Slug)
	b, err := w.RenderEntity(p)
	if err != nil {
		return path, err
	}
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, b) {
		return path, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, err
	}
	return path, os.WriteFile(path, b, 0o644)
}

func splitFrontmatter(s string) (fm, rest string, err error) {
	const marker = "---\n"
	if !strings.HasPrefix(s, marker) {
		return "", "", fmt.Errorf("entity page missing frontmatter")
	}
	body := s[len(marker):]
	end := strings.Index(body, marker)
	if end < 0 {
		return "", "", fmt.Errorf("entity page frontmatter not closed")
	}
	return body[:end], body[end+len(marker):], nil
}

func section(s, begin, end string) (string, bool) {
	i := strings.Index(s, begin)
	if i < 0 {
		return "", false
	}
	rest := s[i+len(begin):]
	j := strings.Index(rest, end)
	if j < 0 {
		return "", false
	}
	return rest[:j], true
}

// escapeCell backslash-escapes pipes and backslashes so cell content can
// never break the table grammar; splitRow reverses it.
func escapeCell(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '\\' || r == '|' {
			b.WriteRune('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// splitRow splits a table row on unescaped pipes, unescaping as it scans.
func splitRow(ln string) []string {
	var cells []string
	var cur strings.Builder
	escaped := false
	for _, r := range ln {
		switch {
		case escaped:
			cur.WriteRune(r)
			escaped = false
		case r == '\\':
			escaped = true
		case r == '|':
			cells = append(cells, strings.TrimSpace(cur.String()))
			cur.Reset()
		default:
			cur.WriteRune(r)
		}
	}
	cells = append(cells, strings.TrimSpace(cur.String()))
	if len(cells) >= 2 {
		cells = cells[1 : len(cells)-1] // rows start and end with |
	}
	return cells
}

func confCell(c float64) string { return strconv.FormatFloat(c, 'f', 2, 64) }

func windowCell(from, to string) string {
	if from == "" && to == "" {
		return ""
	}
	return from + ".." + to
}

func titleFromSlug(slug string) string {
	parts := strings.Split(slug, "-")
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}
